### Import csv file

In [1]:
import pandas as pd

In [2]:
csv_file = "ny_emissions_source.csv"
emissions_df = pd.read_csv(csv_file)
emissions_df.head()

,STATE_FIPS,STATE_ABBR,tier1_code,tier1_description,pollutant_code,emissions90,emissions96,emissions97,emissions98,emissions99,...,emissions08,emissions09,emissions10,emissions11,emissions12,emissions13,emissions14,emissions15,emissions16,emissions17
0,1,AL,1,FUEL COMB. ELEC. UTIL.,CO,6.86859,8.06884,8.04705,8.12158,11.515260,...,11.439576,10.966844,10.494112,9.957645,9.642311,9.326977,9.011643,9.011643,9.011643,9.011643
1,1,AL,1,FUEL COMB. ELEC. UTIL.,NH3,NaN,0.01516,0.01605,0.01597,0.016510,...,0.539198,0.522572,0.505946,0.489319,0.488463,0.487606,0.486749,0.486749,0.486749,0.486749
2,1,AL,1,FUEL COMB. ELEC. UTIL.,NOX,187.79386,219.00900,209.98918,198.66722,186.387100,...,113.032992,96.009230,78.879465,61.687148,57.768312,53.849475,49.930638,44.893997,27.631909,21.307058
3,1,AL,1,FUEL COMB. ELEC. UTIL.,PM10,8.85994,9.28102,8.83472,8.37946,29.217020,...,5.137091,5.876249,6.615407,7.323322,6.469981,5.616641,4.763300,4.763300,4.763300,4.763300
4,1,AL,1,FUEL COMB. ELEC. UTIL.,PM25,3.60246,4.36618,4.23529,4.00666,25.092193,...,2.755614,3.465757,4.175901,4.866091,4.407621,3.949151,3.490680,3.490680,3.490680,3.490680

### Filter for NY data

In [3]:
emissions_df = emissions_df.loc[emissions_df["STATE_ABBR"] == "NY", :]
emissions_df

,STATE_FIPS,STATE_ABBR,tier1_code,tier1_description,pollutant_code,emissions90,emissions96,emissions97,emissions98,emissions99,...,emissions08,emissions09,emissions10,emissions11,emissions12,emissions13,emissions14,emissions15,emissions16,emissions17
2664,36,NY,1,FUEL COMB. ELEC. UTIL.,CO,16.03086,13.24499,15.45828,16.91718,13.293890,...,13.645393,12.736989,11.828584,10.920179,14.153275,17.386371,20.619467,20.619467,20.619467,20.619467
2665,36,NY,1,FUEL COMB. ELEC. UTIL.,NH3,NaN,0.53010,0.59650,0.74865,1.248295,...,1.659857,1.421432,1.183007,0.940860,0.787398,0.633937,0.480475,0.480475,0.480475,0.480475
2666,36,NY,1,FUEL COMB. ELEC. UTIL.,NOX,182.92023,114.39085,124.65004,139.60816,94.278693,...,36.218654,32.155848,28.093041,23.079955,21.111937,19.143920,17.175902,11.149472,9.572080,7.097014
2667,36,NY,1,FUEL COMB. ELEC. UTIL.,PM10,5.93876,2.59551,2.66421,2.67177,15.404163,...,5.376017,4.354777,3.333536,2.312296,2.054001,1.795706,1.537411,1.537411,1.537411,1.537411
2668,36,NY,1,FUEL COMB. ELEC. UTIL.,PM25,3.35984,1.56975,1.64099,1.66977,14.231397,...,3.002750,2.533685,2.064619,1.595554,1.415556,1.235559,1.055561,1.055561,1.055561,1.055561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4935,36,NY,16,PRESCRIBED FIRES,NOX,NaN,NaN,NaN,NaN,NaN,...,0.102943,0.095350,0.087757,0.080164,0.094678,0.109191,0.123705,0.123705,0.123705,0.123705
4936,36,NY,16,PRESCRIBED FIRES,PM10,NaN,NaN,NaN,NaN,NaN,...,0.573859,0.564482,0.555106,0.545730,0.655889,0.766049,0.876208,0.876208,0.876208,0.876208
4937,36,NY,16,PRESCRIBED FIRES,PM25,NaN,NaN,NaN,NaN,NaN,...,0.486321,0.478375,0.470429,0.462483,0.555838,0.649193,0.742549,0.742549,0.742549,0.742549
4938,36,NY,16,PRESCRIBED FIRES,SO2,NaN,NaN,NaN,NaN,NaN,...,0.049469,0.047050,0.044631,0.042212,0.050279,0.058345,0.066412,0.066412,0.066412,0.066412
4939,36,NY,16,PRESCRIBED FIRES,VOC,NaN,NaN,NaN,NaN,NaN,...,1.278026,1.269178,1.260330,1.251482,1.507498,1.763514,2.019529,2.019529,2.019529,2.019529

### Clean up columns

In [4]:
emissions_df = emissions_df.drop(columns = ["STATE_FIPS", "STATE_ABBR"])
emissions_df = emissions_df.rename(columns = {"emissions90": "1990",
                                             "emissions96": "1996",
                                             "emissions97": "1997",
                                             "emissions98": "1998",
                                             "emissions99": "1999",
                                             "emissions00": "2000",
                                             "emissions01": "2001",
                                             "emissions02": "2002",
                                             "emissions03": "2003",
                                             "emissions04": "2004",
                                             "emissions05": "2005",
                                             "emissions06": "2006",
                                             "emissions07": "2007",
                                             "emissions08": "2008",
                                             "emissions09": "2009",
                                             "emissions10": "2010",
                                             "emissions11": "2011",
                                             "emissions12": "2012",
                                             "emissions13": "2013",
                                             "emissions14": "2014",
                                             "emissions15": "2015",
                                             "emissions16": "2016",
                                             "emissions17": "2017"})
emissions_df.head()

,tier1_code,tier1_description,pollutant_code,1990,1996,1997,1998,1999,2000,2001,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
2664,1,FUEL COMB. ELEC. UTIL.,CO,16.03086,13.24499,15.45828,16.91718,13.293890,12.497987,12.917591,...,13.645393,12.736989,11.828584,10.920179,14.153275,17.386371,20.619467,20.619467,20.619467,20.619467
2665,1,FUEL COMB. ELEC. UTIL.,NH3,NaN,0.53010,0.59650,0.74865,1.248295,1.245109,1.244441,...,1.659857,1.421432,1.183007,0.940860,0.787398,0.633937,0.480475,0.480475,0.480475,0.480475
2666,1,FUEL COMB. ELEC. UTIL.,NOX,182.92023,114.39085,124.65004,139.60816,94.278693,94.866671,90.582678,...,36.218654,32.155848,28.093041,23.079955,21.111937,19.143920,17.175902,11.149472,9.572080,7.097014
2667,1,FUEL COMB. ELEC. UTIL.,PM10,5.93876,2.59551,2.66421,2.67177,15.404163,16.484558,16.592244,...,5.376017,4.354777,3.333536,2.312296,2.054001,1.795706,1.537411,1.537411,1.537411,1.537411
2668,1,FUEL COMB. ELEC. UTIL.,PM25,3.35984,1.56975,1.64099,1.66977,14.231397,15.189639,15.085621,...,3.002750,2.533685,2.064619,1.595554,1.415556,1.235559,1.055561,1.055561,1.055561,1.055561